package main

import (
	"context"
	"errors"
	"fmt"
	"log"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/wailsapp/wails/v3/pkg/application"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"

	"github.com/a3tai/library/internal/aimeta"
	"github.com/a3tai/library/internal/mcpserver"
)

// chatDebug toggles verbose per-turn logging. On by default — once the
// chat pipeline is stable again, set LIBRARY_CHAT_DEBUG=0 to silence.
var chatDebug = envUnsetOrNotZero("LIBRARY_CHAT_DEBUG")

// chatLogf emits a [chat turnID] prefixed line so successive turns can be
// untangled in the dev log.
func chatLogf(turnID, format string, args ...any) {
	if !chatDebug {
		return
	}
	log.Printf("[chat %s] "+format, append([]any{turnID}, args...)...)
}

// chatTurnSeq names each in-flight chat turn for the frontend so it can
// correlate streaming deltas with the right composer.
var chatTurnSeq atomic.Uint64

// chat:turn:* events emitted to the frontend during a streaming turn.
const (
	chatEventStart = "chat:turn:start" // {turnId}
	chatEventDelta = "chat:turn:delta" // {turnId, content}
	chatEventRound = "chat:turn:round" // {turnId} — round ended (with tool_calls); reset frontend draft buffer
	chatEventEnd   = "chat:turn:end"   // {turnId, error?} — flip frontend busy flag off
)

// emitChatEvent is a no-op when the Wails app isn't initialised yet (e.g.
// during tests); otherwise it broadcasts to all listening windows.
func emitChatEvent(name string, payload map[string]any) {
	app := application.Get()
	if app == nil {
		return
	}
	if chatDebug {
		// Don't dump full payload for delta events — content can be huge.
		// Log size + first byte of content for spot-checking. For other
		// events the payload is small enough to print verbatim.
		if name == chatEventDelta {
			turnID, _ := payload["turnId"].(string)
			content, _ := payload["content"].(string)
			head := content
			if len(head) > 40 {
				head = head[:40] + "…"
			}
			log.Printf("[chat %s] emit %s size=%d %q", turnID, name, len(content), head)
		} else {
			turnID, _ := payload["turnId"].(string)
			log.Printf("[chat %s] emit %s %v", turnID, name, payload)
		}
	}
	app.Event.Emit(name, payload)
}

// ChatMessage is the wire shape exchanged with the frontend. Mirrors a
// subset of the OpenAI chat schema so the frontend can render assistant
// turns with their tool-call traces.
type ChatMessage struct {
	Role       string         `json:"role"`
	Content    string         `json:"content,omitempty"`
	Name       string         `json:"name,omitempty"`
	ToolCallID string         `json:"toolCallId,omitempty"`
	ToolCalls  []ChatToolCall `json:"toolCalls,omitempty"`
}

type ChatToolCall struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Arguments string `json:"arguments"` // raw JSON the model emitted
	Result    string `json:"result,omitempty"`
	Error     string `json:"error,omitempty"`
}

// ChatRequest is what the frontend sends to start one turn.
type ChatRequest struct {
	BookID  string        `json:"bookId"`
	Message string        `json:"message"`
	History []ChatMessage `json:"history"`
	// TurnID is generated by the frontend so it can correlate streaming
	// chat:turn:* events with the right composer. Optional; the backend
	// falls back to an auto-incrementing id when empty.
	TurnID string `json:"turnId,omitempty"`
}

// ChatResponse carries the assistant's final reply plus the tool trace.
type ChatResponse struct {
	Reply     ChatMessage    `json:"reply"`
	History   []ChatMessage  `json:"history"`
	ToolCalls []ChatToolCall `json:"toolCalls"`
	Model     string         `json:"model"`
	Available bool           `json:"available"`
	Error     string         `json:"error,omitempty"`
}

// ChatAvailable lets the frontend probe whether LM Studio is reachable
// without launching a turn.
func (s *LibraryService) ChatAvailable() bool {
	if s.ai == nil {
		return false
	}
	ctx, cancel := context.WithTimeout(context.Background(), 1500*time.Millisecond)
	defer cancel()
	return s.ai.Available(ctx)
}

// ChatTurn runs one round of conversation. The model is given a
// book-grounded system prompt and access to the library's MCP tools; if it
// emits tool_calls, we execute them in-process via the MCP server and feed
// the results back, looping up to a small bound to prevent runaways.
func (s *LibraryService) ChatTurn(req ChatRequest) (ChatResponse, error) {
	// Root span for the whole turn. Sub-spans wrap each round, each
	// tool call, and the LM Studio streaming call. Attributes carry the
	// turn id, book id, model, and final shape (history length, reply
	// content length, error).
	turnSpanCtx, turnSpan := tracer().Start(context.Background(), "chat.turn",
		trace.WithAttributes(
			attribute.String("a3t-library.turn_id", strings.TrimSpace(req.TurnID)),
			attribute.String("a3t-library.book_id", req.BookID),
			attribute.Int("a3t-library.history_in", len(req.History)),
			attribute.Int("a3t-library.message_len", len(req.Message)),
		),
	)
	defer turnSpan.End()

	if s.ai == nil {
		spanErr(turnSpan, fmt.Errorf("ai client not configured"))
		return ChatResponse{Available: false, Error: "AI client is not configured"}, nil
	}
	turnSpan.SetAttributes(attribute.String("a3t-library.model", s.ai.Model))

	book, err := s.store.GetBook(turnSpanCtx, req.BookID)
	if err != nil {
		spanErr(turnSpan, err)
		return ChatResponse{Available: true, Error: err.Error()}, nil
	}

	// Cached per-book; cheap on repeat turns and keeps the system-prompt
	// bytes byte-stable so the local LLM's KV cache prefix survives.
	toc, _ := s.BookTOC(book.ID)

	tools := buildOpenAITools()
	messages := []aimeta.Message{
		{Role: "system", Content: chatSystemPrompt(book, toc)},
	}
	for _, m := range req.History {
		messages = append(messages, toAI(m))
	}
	messages = append(messages, aimeta.Message{Role: "user", Content: strings.TrimSpace(req.Message)})

	mcp := mcpserver.New(s.store)
	// 8 minutes covers the worst case observed locally: a small/slow model
	// chaining 6+ tool rounds with ~30s of thinking between each. The
	// previous 3-minute cap was killing long agent loops just as the
	// model was starting its final reply. Built on top of the turn span
	// context so per-round spans inherit the turn id automatically.
	turnCtx, cancel := context.WithTimeout(turnSpanCtx, 8*time.Minute)
	defer cancel()

	turnID := strings.TrimSpace(req.TurnID)
	if turnID == "" {
		turnID = strconv.FormatUint(chatTurnSeq.Add(1), 10)
	}
	chatLogf(turnID, "start: book=%s history=%d message=%q", book.ID, len(req.History), truncateText(req.Message, 120))
	emitChatEvent(chatEventStart, map[string]any{"turnId": turnID})
	defer func() {
		chatLogf(turnID, "defer end")
		// chatEventEnd is emitted unconditionally so the frontend always
		// flips its busy flag back. Errors come through the synchronous
		// return in resp.Error.
		emitChatEvent(chatEventEnd, map[string]any{"turnId": turnID})
	}()

	resp := ChatResponse{Available: true, History: append([]ChatMessage{}, req.History...)}
	resp.History = append(resp.History, ChatMessage{Role: "user", Content: strings.TrimSpace(req.Message)})

	// maxToolRounds caps how many search-and-respond cycles the model gets
	// before we hard-stop. Bumped from 4 to 8 because narrow first-pass
	// queries (esp. against FTS-only libraries) often need 2-3 reformulations
	// before the model has enough grounded context to answer.
	// Discover the chat model's context window so we can stay safely below
	// it. LM Studio's /api/v0/models endpoint surfaces it when available;
	// callers without that endpoint get a conservative default.
	contextBudget := s.resolveChatBudget(turnCtx, s.ai.Model)
	chatLogf(turnID, "context budget: %d tokens (model=%s)", contextBudget, s.ai.Model)

	// Loop detector — small local models often get stuck calling the same
	// tool with the same/similar args after a search returns no results.
	// We track a fingerprint of (tool_name + first 200 bytes of args), and
	// when the same fingerprint shows up 3+ times across rounds, we inject
	// a system breadcrumb telling the model to answer with what it has.
	// `emptyResultStreak` separately counts consecutive empty-ish results;
	// 2 in a row also forces the model to stop searching.
	toolCallSeen := map[string]int{}
	emptyResultStreak := 0

	const maxToolRounds = 8
	for round := 0; round < maxToolRounds; round++ {
		roundCtx, roundSpan := tracer().Start(turnCtx, "chat.round",
			trace.WithAttributes(attribute.Int("a3t-library.round", round)),
		)
		// The body of this block uses roundCtx and roundSpan; the outer
		// loop continues with turnCtx. We end the span explicitly at the
		// bottom of each iteration so it gets the final attributes.

		if round > 0 {
			// Older tool results are no longer load-bearing for the model's
			// next reasoning step; stubbing them caps prefill growth across
			// rounds without losing the recent batch.
			elideOldToolResults(messages)
			// Tell the frontend the previous round closed so it resets its
			// in-flight assistant draft buffer before the next round streams.
			emitChatEvent(chatEventRound, map[string]any{"turnId": turnID})
		}

		// Compact before sending if we're over budget. Compaction keeps the
		// system prompt + tail and folds the middle into a structured
		// summary system message.
		sent, compacted := compactMessagesToBudget(messages, contextBudget)
		if compacted {
			chatLogf(turnID, "round=%d compacted: %d → %d tokens (%d msgs → %d msgs)",
				round, messagesTokens(messages), messagesTokens(sent), len(messages), len(sent))
			emitChatEvent("chat:turn:compacted", map[string]any{
				"turnId":    turnID,
				"before":    messagesTokens(messages),
				"after":     messagesTokens(sent),
				"msgBefore": len(messages),
				"msgAfter":  len(sent),
			})
		}
		chatLogf(turnID, "round=%d begin: messages=%d est_prompt_tokens=%d budget=%d",
			round, len(sent), messagesTokens(sent), contextBudget)

		deltaCount := 0
		deltaBytes := 0
		out, err := s.ai.ChatStream(turnCtx, sent, tools, func(delta string) {
			deltaCount++
			deltaBytes += len(delta)
			emitChatEvent(chatEventDelta, map[string]any{"turnId": turnID, "content": delta})
		})
		if err != nil {
			chatLogf(turnID, "round=%d ChatStream error: %v", round, err)
			// Adaptive retry: if the model rejects with a context-size
			// error, halve the budget and try one more time with a more
			// aggressively compacted prompt. Most often this happens when
			// our estimate underestimated the real token cost (BPE tokens
			// for code/JSON can be 1.5-2x what bytes/3.5 predicts).
			if isContextError(err) && contextBudget > 1500 {
				contextBudget = contextBudget / 2
				chatLogf(turnID, "round=%d context overflow — retrying at budget=%d", round, contextBudget)
				sent2, _ := compactMessagesToBudget(messages, contextBudget)
				out, err = s.ai.ChatStream(turnCtx, sent2, tools, func(delta string) {
					deltaCount++
					deltaBytes += len(delta)
					emitChatEvent(chatEventDelta, map[string]any{"turnId": turnID, "content": delta})
				})
			}
		}
		if err != nil {
			// "Context size exceeded" from LM Studio shows up here. Surface
			// it as a friendlier message that hints at the workaround
			// (smaller history / load a larger-context model).
			resp.Error = friendlyChatError(err)
			spanErr(roundSpan, err)
			roundSpan.End()
			return resp, nil
		}
		chatLogf(turnID, "round=%d stream complete: deltas=%d delta_bytes=%d content_len=%d tool_calls=%d",
			round, deltaCount, deltaBytes, len(out.Message.Content), len(out.Message.ToolCalls))

		resp.Model = out.Model

		// Always record the assistant turn (with any tool_calls) in history.
		assistant := fromAI(out.Message)
		resp.History = append(resp.History, assistant)
		messages = append(messages, out.Message)

		if len(out.Message.ToolCalls) == 0 {
			chatLogf(turnID, "round=%d final reply: content_len=%d", round, len(out.Message.Content))
			resp.Reply = assistant
			roundSpan.SetAttributes(
				attribute.Int("a3t-library.deltas", deltaCount),
				attribute.Int("a3t-library.delta_bytes", deltaBytes),
				attribute.Int("a3t-library.content_len", len(out.Message.Content)),
				attribute.Bool("a3t-library.final_reply", true),
			)
			roundSpan.End()
			return resp, nil
		}

		// Execute the round's tool calls in parallel — each one is a local
		// SQLite read through the in-process MCP server. Results are stitched
		// back into the response/messages slices in the original call order
		// so the conversation transcript stays deterministic. The trace
		// returned to the frontend keeps the full result (up to uiResultMax)
		// for the user; the message fed back to the LLM is truncated harder
		// so prefill stays bounded across tool rounds.
		const (
			uiResultMax  = 8000
			llmResultMax = 3000
		)
		results := make([]string, len(out.Message.ToolCalls))
		errs := make([]error, len(out.Message.ToolCalls))
		var wg sync.WaitGroup
		for i, call := range out.Message.ToolCalls {
			wg.Add(1)
			go func(i int, call aimeta.ToolCall) {
				defer wg.Done()
				// Each tool call gets its own span anchored under the
				// round span so traces show a per-tool latency
				// breakdown.
				_, toolSpan := tracer().Start(roundCtx, "tool.call",
					trace.WithAttributes(
						attribute.String("a3t-library.tool", call.Function.Name),
						attribute.Int("a3t-library.args_len", len(call.Function.Arguments)),
					),
				)
				results[i], errs[i] = executeMCPTool(mcp, call)
				toolSpan.SetAttributes(attribute.Int("a3t-library.result_len", len(results[i])))
				spanErr(toolSpan, errs[i])
				toolSpan.End()
			}(i, call)
		}
		wg.Wait()
		// Loop-detector accounting. A "fingerprint" is (tool name + first
		// ~200 bytes of args) — caught both literal duplicates and
		// near-duplicates with shifted whitespace.
		roundHadEmpty := false
		roundHadDup := false
		for i, call := range out.Message.ToolCalls {
			argHead := call.Function.Arguments
			if len(argHead) > 200 {
				argHead = argHead[:200]
			}
			fp := call.Function.Name + "|" + argHead
			toolCallSeen[fp]++
			if errs[i] != nil {
				chatLogf(turnID, "round=%d tool=%s args=%q error: %v", round, call.Function.Name, truncateText(call.Function.Arguments, 80), errs[i])
			} else {
				chatLogf(turnID, "round=%d tool=%s args=%q result_len=%d seen=%d",
					round, call.Function.Name, truncateText(call.Function.Arguments, 80), len(results[i]), toolCallSeen[fp])
			}
			// "Empty-ish" = literal `[]`, `{}`, empty string, or just a
			// "no result" stub. The model interprets these as "I should
			// try a different query", which fuels the loop.
			trimmed := strings.TrimSpace(results[i])
			if errs[i] == nil && (trimmed == "" || trimmed == "[]" || trimmed == "{}" || trimmed == "null") {
				roundHadEmpty = true
			}
			if toolCallSeen[fp] >= 3 {
				roundHadDup = true
			}
		}
		if roundHadEmpty {
			emptyResultStreak++
		} else {
			emptyResultStreak = 0
		}

		for i, call := range out.Message.ToolCalls {
			trace := ChatToolCall{
				ID:        call.ID,
				Name:      call.Function.Name,
				Arguments: call.Function.Arguments,
			}
			if errs[i] != nil {
				trace.Error = errs[i].Error()
			} else {
				trace.Result = truncateText(results[i], uiResultMax)
			}
			resp.ToolCalls = append(resp.ToolCalls, trace)

			llmContent := truncateText(results[i], llmResultMax)
			messages = append(messages, aimeta.Message{
				Role:       "tool",
				ToolCallID: call.ID,
				Name:       call.Function.Name,
				Content:    llmContent + iff(trace.Error != "", "\n[error: "+trace.Error+"]"),
			})
			resp.History = append(resp.History, ChatMessage{
				Role:       "tool",
				ToolCallID: call.ID,
				Name:       call.Function.Name,
				Content:    trace.Result,
			})
		}

		// Loop break: if this round either repeated a tool call we've now
		// seen 3+ times, or if it produced empty results 2+ rounds in a
		// row, inject a system breadcrumb so the next ChatStream forces
		// the model to answer with what it has rather than search again.
		if roundHadDup || emptyResultStreak >= 2 {
			reason := "tools are returning no new information"
			if roundHadDup {
				reason = "the same tool query has been repeated multiple times"
			}
			breadcrumb := aimeta.Message{
				Role:    "system",
				Content: "[loop-guard] " + reason + ". Do not call any more tools — instead, write your final answer to the user using the metadata in the system prompt and whatever tool results you already have. If the question can't be fully answered, say what you do know and what's missing.",
			}
			messages = append(messages, breadcrumb)
			chatLogf(turnID, "round=%d loop-guard tripped (dup=%v emptyStreak=%d) — injecting breadcrumb", round, roundHadDup, emptyResultStreak)
			roundSpan.SetAttributes(attribute.Bool("a3t-library.loop_guard", true))
		}
		roundSpan.SetAttributes(
			attribute.Int("a3t-library.deltas", deltaCount),
			attribute.Int("a3t-library.delta_bytes", deltaBytes),
			attribute.Int("a3t-library.content_len", len(out.Message.Content)),
			attribute.Int("a3t-library.tool_calls", len(out.Message.ToolCalls)),
		)
		roundSpan.End()
	}
	if resp.Reply.Role == "" {
		resp.Error = "model exceeded the tool-call round limit"
	}
	turnSpan.SetAttributes(
		attribute.Int("a3t-library.history_out", len(resp.History)),
		attribute.Int("a3t-library.reply_content_len", len(resp.Reply.Content)),
		attribute.String("a3t-library.error", resp.Error),
	)
	if resp.Error != "" {
		spanErr(turnSpan, errors.New(resp.Error))
	}
	chatLogf(turnID, "return: history=%d reply_role=%q reply_content_len=%d error=%q", len(resp.History), resp.Reply.Role, len(resp.Reply.Content), resp.Error)
	return resp, nil
}

// approxTokens is a coarse byte→token estimator (~4 bytes per token for
// English-heavy prose; tool JSON is closer to 3 because it has lots of
// short separators, so we use 3.5 as a middle ground via 7/2). Good
// enough for budget guards — we leave a generous headroom margin so
// underestimates don't bite.
